import type { Metadata } from "next";
import "./globals.css";

import {paragraphFont} from "@/assets/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${paragraphFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
